# Generated by Django 5.0.14 on 2026-01-21 18:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_session_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ログインセッション開始時刻'),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_code_attempts',
            field=models.IntegerField(default=0, verbose_name='認証コード検証失敗回数'),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_code_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='認証コード有効期限'),
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='トークン')),
                ('expires_at', models.DateTimeField(verbose_name='有効期限')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='使用日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'パスワード再設定トークン',
                'verbose_name_plural': 'パスワード再設定トークン',
                'db_table': 'password_reset_tokens',
                'indexes': [models.Index(fields=['user', 'expires_at'], name='password_re_user_id_13cacb_idx'), models.Index(fields=['token'], name='password_re_token_060a1f_idx')],
            },
        ),
    ]
