# Generated by Django 5.0.14 on 2025-12-12 12:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=200, verbose_name='会社名')),
                ('company_email', models.EmailField(max_length=254, verbose_name='メールアドレス')),
                ('tax_id', models.CharField(blank=True, max_length=20, verbose_name='法人番号')),
                ('service_areas', models.JSONField(blank=True, default=list, verbose_name='事業所在地')),
                ('max_luggage_capacity', models.PositiveIntegerField(default=20, verbose_name='最大荷物個数')),
                ('operating_hours_start', models.TimeField(default='09:00', verbose_name='営業開始時間')),
                ('operating_hours_end', models.TimeField(default='17:00', verbose_name='営業終了時間')),
                ('operating_days', models.CharField(default='1111111', max_length=7, verbose_name='営業日')),
                ('pricing_rules', models.JSONField(blank=True, default=dict, verbose_name='料金設定')),
                ('total_orders_completed', models.PositiveIntegerField(default=0, verbose_name='総注文数')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='総売上')),
                ('is_approved', models.BooleanField(default=False, verbose_name='承認状態')),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='有効/無効')),
                ('deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='無効化日')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('stripe_account_id', models.CharField(blank=True, default='', max_length=255, verbose_name='StripeアカウントID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '事業者プロフィール',
                'verbose_name_plural': '事業者プロフィール',
                'db_table': 'business_profiles',
            },
        ),
    ]
