# Generated by Django 5.0.14 on 2026-08-30 17:37

import business_owners.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_type', models.CharField(choices=[('company', '法人'), ('individual', '個人事業主')], default='individual', max_length=20, verbose_name='事業形態')),
                ('company_name', models.CharField(max_length=100, verbose_name='会社名')),
                ('company_email', models.EmailField(max_length=254, verbose_name='メールアドレス')),
                ('tax_id', models.CharField(blank=True, max_length=20, verbose_name='法人番号')),
                ('invoice_registration_number', models.CharField(blank=True, default='', help_text='「T」＋13桁の数字（例: T1234567890123）。任意。', max_length=14, validators=[business_owners.models.validate_invoice_registration_number], verbose_name='適格請求書発行事業者登録番号')),
                ('rep_last_name_kanji', models.CharField(blank=True, max_length=50, verbose_name='代表者姓（漢字）')),
                ('rep_first_name_kanji', models.CharField(blank=True, max_length=50, verbose_name='代表者名（漢字）')),
                ('rep_last_name_kana', models.CharField(blank=True, max_length=50, verbose_name='代表者姓（カナ）')),
                ('rep_first_name_kana', models.CharField(blank=True, max_length=50, verbose_name='代表者名（カナ）')),
                ('service_areas', models.JSONField(blank=True, default=list, verbose_name='集荷地域')),
                ('operating_hours_start', models.TimeField(default='09:00', verbose_name='営業開始時間')),
                ('operating_hours_end', models.TimeField(default='17:00', verbose_name='営業終了時間')),
                ('operating_days', models.CharField(default='1111111', max_length=7, verbose_name='営業日')),
                ('nth_weekday_holidays', models.JSONField(blank=True, default=list, help_text='["週番号-曜日番号", ...] 週:1-4, 曜日:0=月〜6=日', verbose_name='第N週曜日定休日')),
                ('daily_max_luggage', models.IntegerField(default=0, help_text='-1の場合は制限なし。0の場合は予約不可。1以上で上限値。', verbose_name='1日の最大荷物個数')),
                ('temporary_closures', models.JSONField(blank=True, default=list, help_text='ISO形式の日付文字列リスト例: ["2026-04-10", "2026-05-03"]', verbose_name='臨時休業日')),
                ('public_info_consent_at', models.DateTimeField(blank=True, help_text='特定商取引法に基づく表記とプライバシーポリシーをユーザーに表示することへ同意した日時', null=True, verbose_name='公開情報表示同意日時')),
                ('booking_transaction_law_acknowledged_version', models.CharField(blank=True, help_text='ISO 8601 形式の日付（YYYY-MM-DD）。null の場合は未確認。', max_length=10, null=True, verbose_name='確認済み予約サイト特商法テンプレートバージョン')),
                ('booking_transaction_law_acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='予約サイト特商法テンプレート確認日時')),
                ('booking_privacy_acknowledged_version', models.CharField(blank=True, help_text='ISO 8601 形式の日付（YYYY-MM-DD）。null の場合は未確認。', max_length=10, null=True, verbose_name='確認済み予約サイトプライバシーポリシーテンプレートバージョン')),
                ('booking_privacy_acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='予約サイトプライバシーポリシーテンプレート確認日時')),
                ('terms_agreed_version', models.CharField(blank=True, help_text='ISO 8601 形式の日付（YYYY-MM-DD）。null の場合は未同意。', max_length=10, null=True, verbose_name='同意済み利用規約バージョン')),
                ('terms_agreed_at', models.DateTimeField(blank=True, null=True, verbose_name='利用規約同意日時')),
                ('privacy_agreed_version', models.CharField(blank=True, help_text='ISO 8601 形式の日付（YYYY-MM-DD）。null の場合は未同意。', max_length=10, null=True, verbose_name='同意済みプライバシーポリシーバージョン')),
                ('privacy_agreed_at', models.DateTimeField(blank=True, null=True, verbose_name='プライバシーポリシー同意日時')),
                ('pricing_rules', models.JSONField(blank=True, default=dict, verbose_name='料金設定')),
                ('settings_draft', models.JSONField(blank=True, default=None, null=True, verbose_name='事業設定の一時保存')),
                ('settings_draft_saved_at', models.DateTimeField(blank=True, null=True, verbose_name='事業設定の一時保存日時')),
                ('pricing_draft', models.JSONField(blank=True, default=None, null=True, verbose_name='料金設定の一時保存')),
                ('pricing_draft_saved_at', models.DateTimeField(blank=True, null=True, verbose_name='料金設定の一時保存日時')),
                ('is_active', models.BooleanField(default=True, help_text='事業者が有効かどうかを示します。プロフィールを削除する代わりに選択を解除してください。', verbose_name='有効')),
                ('deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='無効化日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('stripe_account_id', models.CharField(blank=True, default=None, max_length=255, null=True, unique=True, verbose_name='StripeアカウントID')),
                ('stripe_address_cache', models.TextField(blank=True, default='', verbose_name='Stripe所在地キャッシュ')),
                ('stripe_support_email_cache', models.CharField(blank=True, default='', max_length=254, verbose_name='Stripe問い合わせメールキャッシュ')),
                ('stripe_support_phone_cache', models.CharField(blank=True, default='', max_length=50, verbose_name='Stripe電話番号キャッシュ')),
                ('stripe_representative_name_cache', models.CharField(blank=True, default='', max_length=200, verbose_name='Stripe代表者名キャッシュ')),
                ('stripe_company_name_en_cache', models.CharField(blank=True, default='', max_length=255, verbose_name='Stripe会社名英語表記キャッシュ')),
                ('stripe_info_cached_at', models.DateTimeField(blank=True, null=True, verbose_name='Stripe事業者情報キャッシュ更新日時')),
                ('stripe_review_status', models.CharField(choices=[('unknown', '未取得'), ('incomplete', '入力未完了'), ('pending', '審査中'), ('restricted', '要対応'), ('enabled', '利用可能'), ('rejected', '利用不可')], default='unknown', max_length=20, verbose_name='Stripe審査状態')),
                ('stripe_charges_enabled', models.BooleanField(default=False, verbose_name='Stripe決済有効')),
                ('stripe_payouts_enabled', models.BooleanField(default=False, verbose_name='Stripe入金有効')),
                ('stripe_details_submitted', models.BooleanField(default=False, verbose_name='Stripe情報提出済み')),
                ('stripe_disabled_reason', models.CharField(blank=True, default='', max_length=100, verbose_name='Stripe無効化理由')),
                ('stripe_currently_due', models.JSONField(blank=True, default=list, help_text='requirements.currently_due + past_due の項目リスト', verbose_name='Stripe要対応項目')),
                ('stripe_review_status_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Stripe審査状態更新日時')),
                ('subdomain', models.CharField(db_index=True, help_text='3文字以上12文字以内、半角小文字英字のみ', max_length=12, unique=True, validators=[business_owners.models.validate_subdomain], verbose_name='予約フォームのURL')),
            ],
            options={
                'verbose_name': '事業者プロフィール',
                'verbose_name_plural': '事業者プロフィール',
                'db_table': 'business_profiles',
            },
        ),
        migrations.CreateModel(
            name='PayoutDocumentDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payout_id', models.CharField(max_length=255, unique=True, verbose_name='Stripe Payout ID')),
                ('payout_created_at', models.DateTimeField(verbose_name='Payout作成日時')),
                ('arrival_date', models.DateField(blank=True, null=True, verbose_name='入金日')),
                ('payout_amount', models.IntegerField(verbose_name='入金額')),
                ('currency', models.CharField(default='jpy', max_length=3, verbose_name='通貨')),
                ('gross_sales', models.IntegerField(default=0, verbose_name='売上合計')),
                ('platform_fee', models.IntegerField(default=0, verbose_name='プラットフォーム手数料')),
                ('matched_transfer_amount', models.IntegerField(default=0, verbose_name='振込合計')),
                ('adjustment_amount', models.IntegerField(default=0, verbose_name='差額')),
                ('line_items', models.JSONField(default=list, verbose_name='明細行')),
                ('issuer_name', models.CharField(max_length=255, verbose_name='発行者名')),
                ('issuer_address', models.TextField(blank=True, default='', verbose_name='発行者住所')),
                ('issuer_registration_number', models.CharField(blank=True, default='', max_length=14, verbose_name='適格請求書発行事業者登録番号')),
                ('recipient_email', models.EmailField(max_length=254, verbose_name='送信先メールアドレス')),
                ('send_attempts', models.PositiveIntegerField(default=0, verbose_name='送信試行回数')),
                ('processing_started_at', models.DateTimeField(blank=True, null=True, verbose_name='送信処理開始日時')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='送信日時')),
                ('last_err', models.TextField(blank=True, default='', verbose_name='最終エラー')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '入金書類の送信記録',
                'verbose_name_plural': '入金書類の送信記録',
                'db_table': 'payout_document_deliveries',
                'ordering': ['-payout_created_at'],
            },
        ),
        migrations.CreateModel(
            name='RegistrationToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='メールアドレス')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='トークン')),
                ('expires_at', models.DateTimeField(verbose_name='有効期限')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='使用日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': '登録トークン',
                'verbose_name_plural': '登録トークン',
                'db_table': 'registration_tokens',
            },
        ),
    ]
