# Generated by Django 5.0.14 on 2026-08-30 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business_owners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payoutdocumentdelivery',
            name='business_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payout_document_deliveries', to='business_owners.businessprofile', verbose_name='事業者'),
        ),
        migrations.AddIndex(
            model_name='registrationtoken',
            index=models.Index(fields=['email', 'expires_at'], name='registratio_email_295eb8_idx'),
        ),
        migrations.AddIndex(
            model_name='registrationtoken',
            index=models.Index(fields=['token'], name='registratio_token_f3a218_idx'),
        ),
    ]
