# Generated by Django 5.0.14 on 2026-01-11 10:38

import business_owners.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_owners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='subdomain',
            field=models.CharField(db_index=True, default='', help_text='3文字以上12文字以内、半角小文字英字のみ', max_length=12, unique=True, validators=[business_owners.models.validate_subdomain], verbose_name='予約フォームのURL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='company_name',
            field=models.CharField(max_length=100, verbose_name='会社名'),
        ),
        migrations.CreateModel(
            name='RegistrationToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='メールアドレス')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='トークン')),
                ('expires_at', models.DateTimeField(verbose_name='有効期限')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='使用日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': '登録トークン',
                'verbose_name_plural': '登録トークン',
                'db_table': 'registration_tokens',
                'indexes': [models.Index(fields=['email', 'expires_at'], name='registratio_email_295eb8_idx'), models.Index(fields=['token'], name='registratio_token_f3a218_idx')],
            },
        ),
    ]
