# Generated by Django 5.0.14 on 2026-02-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_owners', '0002_businessprofile_subdomain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='business_type',
            field=models.CharField(choices=[('company', '法人'), ('individual', '個人事業主')], default='individual', max_length=20, verbose_name='事業形態'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='rep_first_name_kana',
            field=models.CharField(blank=True, max_length=50, verbose_name='代表者名（カナ）'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='rep_first_name_kanji',
            field=models.CharField(blank=True, max_length=50, verbose_name='代表者名（漢字）'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='rep_last_name_kana',
            field=models.CharField(blank=True, max_length=50, verbose_name='代表者姓（カナ）'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='rep_last_name_kanji',
            field=models.CharField(blank=True, max_length=50, verbose_name='代表者姓（漢字）'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='approval_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='承認日'),
        ),
    ]
