# Generated by Django 5.0.14 on 2026-03-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_owners', '0003_businessprofile_business_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='pricing_draft',
            field=models.JSONField(blank=True, default=None, null=True, verbose_name='料金設定の一時保存'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='pricing_draft_saved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='料金設定の一時保存日時'),
        ),
    ]
