# Generated by Django 5.0.14 on 2026-05-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_owners', '0004_businessprofile_pricing_draft_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessprofile',
            name='max_luggage_capacity',
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='booking_privacy_acknowledged_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='予約サイトプライバシーポリシーテンプレート確認日時'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='booking_privacy_acknowledged_version',
            field=models.CharField(blank=True, help_text='ISO 8601 形式の日付（YYYY-MM-DD）。null の場合は未確認。', max_length=10, null=True, verbose_name='確認済み予約サイトプライバシーポリシーテンプレートバージョン'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='booking_transaction_law_acknowledged_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='予約サイト特商法テンプレート確認日時'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='booking_transaction_law_acknowledged_version',
            field=models.CharField(blank=True, help_text='ISO 8601 形式の日付（YYYY-MM-DD）。null の場合は未確認。', max_length=10, null=True, verbose_name='確認済み予約サイト特商法テンプレートバージョン'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='daily_max_luggage',
            field=models.IntegerField(default=0, help_text='-1の場合は制限なし。0の場合は予約不可。1以上で上限値。', verbose_name='1日の最大荷物個数'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='nth_weekday_holidays',
            field=models.JSONField(blank=True, default=list, help_text='["週番号-曜日番号", ...] 週:1-4, 曜日:0=月〜6=日', verbose_name='第N週曜日定休日'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='privacy_agreed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='プライバシーポリシー同意日時'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='privacy_agreed_version',
            field=models.CharField(blank=True, help_text='ISO 8601 形式の日付（YYYY-MM-DD）。null の場合は未同意。', max_length=10, null=True, verbose_name='同意済みプライバシーポリシーバージョン'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='public_info_consent_at',
            field=models.DateTimeField(blank=True, help_text='特定商取引法に基づく表記とプライバシーポリシーをユーザーに表示することへ同意した日時', null=True, verbose_name='公開情報表示同意日時'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='settings_draft',
            field=models.JSONField(blank=True, default=None, null=True, verbose_name='事業設定の一時保存'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='settings_draft_saved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='事業設定の一時保存日時'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='temporary_closures',
            field=models.JSONField(blank=True, default=list, help_text='ISO形式の日付文字列リスト例: ["2026-04-10", "2026-05-03"]', verbose_name='臨時休業日'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='terms_agreed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='利用規約同意日時'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='terms_agreed_version',
            field=models.CharField(blank=True, help_text='ISO 8601 形式の日付（YYYY-MM-DD）。null の場合は未同意。', max_length=10, null=True, verbose_name='同意済み利用規約バージョン'),
        ),
    ]
