# Generated by Django 5.0.14 on 2026-07-03 02:53

import business_owners.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_owners', '0005_remove_businessprofile_max_luggage_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='invoice_registration_number',
            field=models.CharField(blank=True, default='', help_text='「T」＋13桁の数字（例: T1234567890123）。任意。', max_length=14, validators=[business_owners.models.validate_invoice_registration_number], verbose_name='適格請求書発行事業者登録番号'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='stripe_address_cache',
            field=models.TextField(blank=True, default='', verbose_name='Stripe所在地キャッシュ'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='stripe_info_cached_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Stripe事業者情報キャッシュ更新日時'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='stripe_representative_name_cache',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Stripe代表者名キャッシュ'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='stripe_support_email_cache',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='Stripe問い合わせメールキャッシュ'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='stripe_support_phone_cache',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Stripe電話番号キャッシュ'),
        ),
    ]
