# Generated by Django 5.0.14 on 2026-07-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_owners', '0006_businessprofile_invoice_registration_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='stripe_charges_enabled',
            field=models.BooleanField(default=False, verbose_name='Stripe決済有効'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='stripe_currently_due',
            field=models.JSONField(blank=True, default=list, help_text='requirements.currently_due + past_due の項目リスト', verbose_name='Stripe要対応項目'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='stripe_details_submitted',
            field=models.BooleanField(default=False, verbose_name='Stripe情報提出済み'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='stripe_disabled_reason',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Stripe無効化理由'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='stripe_payouts_enabled',
            field=models.BooleanField(default=False, verbose_name='Stripe入金有効'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='stripe_review_status',
            field=models.CharField(choices=[('unknown', '未取得'), ('incomplete', '入力未完了'), ('pending', '審査中'), ('restricted', '要対応'), ('enabled', '利用可能'), ('rejected', '利用不可')], default='unknown', max_length=20, verbose_name='Stripe審査状態'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='stripe_review_status_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Stripe審査状態更新日時'),
        ),
    ]
