# Generated by Django 5.0.14 on 2026-07-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_owners', '0007_businessprofile_stripe_charges_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='stripe_account_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, unique=True, verbose_name='StripeアカウントID'),
        ),
    ]
