# Generated by Django 5.0.14 on 2026-07-21 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_owners', '0009_payoutdocumentdelivery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payoutdocumentdelivery',
            old_name='last_error',
            new_name='last_err',
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='stripe_company_name_en_cache',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Stripe会社名英語表記キャッシュ'),
        ),
    ]
