# Generated by Django 5.0.14 on 2026-08-22 16:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_owners', '0010_rename_last_error_payoutdocumentdelivery_last_err_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payoutdocumentdelivery',
            options={'ordering': ['-payout_created_at'], 'verbose_name': '入金書類の送信記録', 'verbose_name_plural': '入金書類の送信記録'},
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='approval_date',
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='is_approved',
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='無効化日時'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='is_active',
            field=models.BooleanField(default=True, help_text='事業者が有効かどうかを示します。プロフィールを削除する代わりに選択を解除してください。', verbose_name='有効'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='service_areas',
            field=models.JSONField(blank=True, default=list, verbose_name='集荷地域'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='payoutdocumentdelivery',
            name='adjustment_amount',
            field=models.IntegerField(default=0, verbose_name='差額'),
        ),
        migrations.AlterField(
            model_name='payoutdocumentdelivery',
            name='arrival_date',
            field=models.DateField(blank=True, null=True, verbose_name='入金日'),
        ),
        migrations.AlterField(
            model_name='payoutdocumentdelivery',
            name='business_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payout_document_deliveries', to='business_owners.businessprofile', verbose_name='事業者'),
        ),
        migrations.AlterField(
            model_name='payoutdocumentdelivery',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='payoutdocumentdelivery',
            name='currency',
            field=models.CharField(default='jpy', max_length=3, verbose_name='通貨'),
        ),
        migrations.AlterField(
            model_name='payoutdocumentdelivery',
            name='gross_sales',
            field=models.IntegerField(default=0, verbose_name='売上合計'),
        ),
        migrations.AlterField(
            model_name='payoutdocumentdelivery',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='payoutdocumentdelivery',
            name='issuer_address',
            field=models.TextField(blank=True, default='', verbose_name='発行者住所'),
        ),
        migrations.AlterField(
            model_name='payoutdocumentdelivery',
            name='issuer_name',
            field=models.CharField(max_length=255, verbose_name='発行者名'),
        ),
        migrations.AlterField(
            model_name='payoutdocumentdelivery',
            name='issuer_registration_number',
            field=models.CharField(blank=True, default='', max_length=14, verbose_name='適格請求書発行事業者登録番号'),
        ),
        migrations.AlterField(
            model_name='payoutdocumentdelivery',
            name='last_err',
            field=models.TextField(blank=True, default='', verbose_name='最終エラー'),
        ),
        migrations.AlterField(
            model_name='payoutdocumentdelivery',
            name='line_items',
            field=models.JSONField(default=list, verbose_name='明細行'),
        ),
        migrations.AlterField(
            model_name='payoutdocumentdelivery',
            name='matched_transfer_amount',
            field=models.IntegerField(default=0, verbose_name='振込合計'),
        ),
        migrations.AlterField(
            model_name='payoutdocumentdelivery',
            name='payout_amount',
            field=models.IntegerField(verbose_name='入金額'),
        ),
        migrations.AlterField(
            model_name='payoutdocumentdelivery',
            name='payout_created_at',
            field=models.DateTimeField(verbose_name='Payout作成日時'),
        ),
        migrations.AlterField(
            model_name='payoutdocumentdelivery',
            name='platform_fee',
            field=models.IntegerField(default=0, verbose_name='プラットフォーム手数料'),
        ),
        migrations.AlterField(
            model_name='payoutdocumentdelivery',
            name='processing_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='送信処理開始日時'),
        ),
        migrations.AlterField(
            model_name='payoutdocumentdelivery',
            name='recipient_email',
            field=models.EmailField(max_length=254, verbose_name='送信先メールアドレス'),
        ),
        migrations.AlterField(
            model_name='payoutdocumentdelivery',
            name='send_attempts',
            field=models.PositiveIntegerField(default=0, verbose_name='送信試行回数'),
        ),
        migrations.AlterField(
            model_name='payoutdocumentdelivery',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='送信日時'),
        ),
        migrations.AlterField(
            model_name='payoutdocumentdelivery',
            name='stripe_payout_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='Stripe Payout ID'),
        ),
        migrations.AlterField(
            model_name='payoutdocumentdelivery',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
    ]
