# Generated by Django 5.0.14 on 2026-08-30 17:37

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business_owners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('departure_address', models.TextField(blank=True)),
                ('departure_place_id', models.CharField(blank=True, max_length=255)),
                ('departure_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('departure_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('shift_start', models.TimeField(blank=True, null=True)),
                ('max_daily_stops', models.PositiveSmallIntegerField(blank=True, default=10, null=True, verbose_name='1日の最大訪問数')),
                ('max_daily_luggage_count', models.PositiveSmallIntegerField(blank=True, default=20, null=True, verbose_name='1日の最大荷物個数')),
                ('license_expiry', models.DateField(verbose_name='免許証有効期限')),
                ('operating_days', models.CharField(default='1111111', max_length=7)),
                ('is_available', models.BooleanField(default=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='driver_invites/')),
                ('token_digest', models.CharField(db_index=True, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_invitations', to='business_owners.businessprofile')),
            ],
            options={
                'db_table': 'driver_invitations',
            },
        ),
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, max_length=200, verbose_name='会社名')),
                ('departure_address', models.TextField(blank=True, default='', verbose_name='出発地点')),
                ('departure_place_id', models.CharField(blank=True, default='', max_length=255)),
                ('departure_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('departure_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('shift_start', models.TimeField(blank=True, null=True, verbose_name='稼働開始')),
                ('max_daily_stops', models.PositiveSmallIntegerField(blank=True, default=10, null=True, verbose_name='1日の最大訪問数')),
                ('max_daily_luggage_count', models.PositiveSmallIntegerField(blank=True, default=20, null=True, verbose_name='1日の最大荷物個数')),
                ('operating_days', models.CharField(default='1111111', max_length=7, verbose_name='稼働曜日')),
                ('license_expiry', models.DateField(verbose_name='免許証有効期限')),
                ('is_available', models.BooleanField(default=True, help_text='オンの配達者だけが日次自動割当の候補になります。', verbose_name='自動割当の候補')),
                ('is_active', models.BooleanField(default=True, help_text='配達者が有効かどうかを示します。プロフィールを削除する代わりに選択を解除してください。', verbose_name='有効')),
                ('deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='無効化日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('business_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='business_owners.businessprofile', verbose_name='事業者')),
            ],
            options={
                'verbose_name': '配達者プロフィール',
                'verbose_name_plural': '配達者プロフィール',
                'db_table': 'driver_profiles',
            },
        ),
    ]
