# Generated by Django 5.0.14 on 2025-12-12 16:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business_owners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, max_length=200, verbose_name='会社名')),
                ('license_expiry', models.DateField(verbose_name='免許証有効期限')),
                ('is_available', models.BooleanField(default=True, verbose_name='有効/無効')),
                ('total_deliveries', models.PositiveIntegerField(default=0, verbose_name='総配達数')),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='総売上')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('business_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='business_owners.businessprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '配達者プロフィール',
                'verbose_name_plural': '配達者プロフィール',
                'db_table': 'driver_profiles',
            },
        ),
    ]
