# Generated by Django 5.0.14 on 2026-08-30 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
        migrations.AddIndex(
            model_name='driverinvitation',
            index=models.Index(fields=['business_owner', 'email', 'created_at'], name='driver_invi_busines_1b7611_idx'),
        ),
        migrations.AddIndex(
            model_name='driverinvitation',
            index=models.Index(fields=['email', 'expires_at'], name='driver_invi_email_efde5a_idx'),
        ),
    ]
