# Generated by Django 5.0.14 on 2026-08-09 02:12

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_owners', '0010_rename_last_error_payoutdocumentdelivery_last_err_and_more'),
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='departure_address',
            field=models.TextField(blank=True, default='', verbose_name='出発住所'),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='departure_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='departure_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='departure_place_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='max_daily_luggage_count',
            field=models.PositiveSmallIntegerField(blank=True, default=20, null=True, verbose_name='1日の最大荷物個数'),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='max_daily_stops',
            field=models.PositiveSmallIntegerField(blank=True, default=10, null=True, verbose_name='1日の最大訪問数'),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='operating_days',
            field=models.CharField(default='1111111', max_length=7, verbose_name='稼働曜日'),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='shift_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DriverInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('departure_address', models.TextField(blank=True)),
                ('departure_place_id', models.CharField(blank=True, max_length=255)),
                ('departure_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('departure_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('shift_start', models.TimeField(blank=True, null=True)),
                ('max_daily_stops', models.PositiveSmallIntegerField(blank=True, default=10, null=True, verbose_name='1日の最大訪問数')),
                ('max_daily_luggage_count', models.PositiveSmallIntegerField(blank=True, default=20, null=True, verbose_name='1日の最大荷物個数')),
                ('license_expiry', models.DateField(verbose_name='免許証有効期限')),
                ('operating_days', models.CharField(default='1111111', max_length=7)),
                ('is_available', models.BooleanField(default=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='driver_invites/')),
                ('token_digest', models.CharField(db_index=True, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_invitations', to='business_owners.businessprofile')),
            ],
            options={
                'db_table': 'driver_invitations',
                'indexes': [models.Index(fields=['business_owner', 'email', 'created_at'], name='driver_invi_busines_1b7611_idx'), models.Index(fields=['email', 'expires_at'], name='driver_invi_email_efde5a_idx')],
            },
        ),
    ]
