# Generated by Django 5.0.14 on 2026-08-22 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_owners', '0011_alter_payoutdocumentdelivery_options_and_more'),
        ('drivers', '0002_driverprofile_departure_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='無効化日時'),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='is_active',
            field=models.BooleanField(default=True, help_text='配達者が有効かどうかを示します。プロフィールを削除する代わりに選択を解除してください。', verbose_name='有効'),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='business_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='business_owners.businessprofile', verbose_name='事業者'),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='departure_address',
            field=models.TextField(blank=True, default='', verbose_name='出発地点'),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='is_available',
            field=models.BooleanField(default=True, help_text='オンの配達者だけが日次自動割当の候補になります。', verbose_name='自動割当の候補'),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='shift_start',
            field=models.TimeField(blank=True, null=True, verbose_name='稼働開始'),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
    ]
