# Generated by Django 5.0.14 on 2026-08-25 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_driverprofile_deactivated_at_driverprofile_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverprofile',
            name='total_deliveries',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='total_earnings',
        ),
    ]
