# Generated by Django 5.0.14 on 2025-06-15 03:57

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\+?1?\\d{9,15}$", "Valid phone number required."
                            )
                        ],
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("customer", "旅行者"),
                            ("business_owner", "事業者"),
                            ("delivery_driver", "配達者"),
                            ("admin", "管理者"),
                        ],
                        default="customer",
                        max_length=20,
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "country",
                    models.CharField(blank=True, default="Japan", max_length=50),
                ),
                ("city", models.CharField(blank=True, max_length=50)),
                ("address", models.TextField(blank=True)),
                ("postal_code", models.CharField(blank=True, max_length=10)),
                ("is_verified", models.BooleanField(default=False)),
                ("verification_code", models.CharField(blank=True, max_length=6)),
                ("last_active", models.DateTimeField(auto_now=True)),
                ("email_notifications", models.BooleanField(default=True)),
                ("sms_notifications", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "users",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="BusinessProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=200)),
                (
                    "business_license",
                    models.CharField(blank=True, max_length=50, unique=True),
                ),
                ("tax_number", models.CharField(blank=True, max_length=20)),
                ("service_areas", models.JSONField(blank=True, default=list)),
                ("vehicle_types", models.JSONField(blank=True, default=list)),
                ("max_luggage_capacity", models.PositiveIntegerField(default=10)),
                ("operating_hours_start", models.TimeField(default="08:00")),
                ("operating_hours_end", models.TimeField(default="20:00")),
                ("operating_days", models.CharField(default="1111111", max_length=7)),
                (
                    "base_rate",
                    models.DecimalField(decimal_places=2, default=1000, max_digits=8),
                ),
                (
                    "per_km_rate",
                    models.DecimalField(decimal_places=2, default=100, max_digits=6),
                ),
                ("total_orders_completed", models.PositiveIntegerField(default=0)),
                ("average_rating", models.FloatField(default=0.0)),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("is_approved", models.BooleanField(default=False)),
                ("approval_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Business Profile",
                "verbose_name_plural": "Business Profiles",
                "db_table": "business_profiles",
            },
        ),
        migrations.CreateModel(
            name="CustomerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("frequent_destinations", models.JSONField(blank=True, default=list)),
                (
                    "preferred_luggage_type",
                    models.CharField(
                        choices=[
                            ("suitcase", "スーツケース"),
                            ("backpack", "バックパック"),
                            ("duffel", "ダッフルバッグ"),
                            ("other", "その他"),
                        ],
                        default="suitcase",
                        max_length=20,
                    ),
                ),
                ("total_bookings", models.PositiveIntegerField(default=0)),
                (
                    "total_spent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("loyalty_points", models.PositiveIntegerField(default=0)),
                (
                    "emergency_contact_name",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(blank=True, max_length=15),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer Profile",
                "verbose_name_plural": "Customer Profiles",
                "db_table": "customer_profiles",
            },
        ),
        migrations.CreateModel(
            name="DriverProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("driver_license", models.CharField(max_length=20, unique=True)),
                ("license_expiry", models.DateField()),
                ("vehicle_plate", models.CharField(max_length=10)),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("car", "乗用車"),
                            ("van", "バン"),
                            ("truck", "トラック"),
                            ("motorcycle", "バイク"),
                        ],
                        default="car",
                        max_length=20,
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
                ("current_location_lat", models.FloatField(blank=True, null=True)),
                ("current_location_lng", models.FloatField(blank=True, null=True)),
                ("last_location_update", models.DateTimeField(blank=True, null=True)),
                ("total_deliveries", models.PositiveIntegerField(default=0)),
                ("average_rating", models.FloatField(default=0.0)),
                (
                    "total_earnings",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drivers",
                        to="accounts.businessprofile",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="driver_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Driver Profile",
                "verbose_name_plural": "Driver Profiles",
                "db_table": "driver_profiles",
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["user_type"], name="users_user_ty_578f8f_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="users_email_4b85f2_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["created_at"], name="users_created_6541e9_idx"),
        ),
    ]
