# Generated by Django 5.0.14 on 2025-06-21 21:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="businessprofile",
            options={"verbose_name": "事業者プロフィール", "verbose_name_plural": "事業者プロフィール"},
        ),
        migrations.AlterModelOptions(
            name="customerprofile",
            options={"verbose_name": "顧客プロフィール", "verbose_name_plural": "顧客プロフィール"},
        ),
        migrations.AlterModelOptions(
            name="driverprofile",
            options={"verbose_name": "配達者プロフィール", "verbose_name_plural": "配達者プロフィール"},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "ユーザー", "verbose_name_plural": "ユーザー"},
        ),
        migrations.RemoveField(
            model_name="businessprofile",
            name="average_rating",
        ),
        migrations.RemoveField(
            model_name="businessprofile",
            name="vehicle_types",
        ),
        migrations.RemoveField(
            model_name="customerprofile",
            name="emergency_contact_name",
        ),
        migrations.RemoveField(
            model_name="customerprofile",
            name="emergency_contact_phone",
        ),
        migrations.RemoveField(
            model_name="customerprofile",
            name="frequent_destinations",
        ),
        migrations.RemoveField(
            model_name="customerprofile",
            name="loyalty_points",
        ),
        migrations.RemoveField(
            model_name="customerprofile",
            name="total_bookings",
        ),
        migrations.RemoveField(
            model_name="customerprofile",
            name="total_spent",
        ),
        migrations.RemoveField(
            model_name="driverprofile",
            name="average_rating",
        ),
        migrations.RemoveField(
            model_name="driverprofile",
            name="current_location_lat",
        ),
        migrations.RemoveField(
            model_name="driverprofile",
            name="current_location_lng",
        ),
        migrations.RemoveField(
            model_name="driverprofile",
            name="vehicle_type",
        ),
        migrations.AlterField(
            model_name="customerprofile",
            name="preferred_luggage_type",
            field=models.CharField(
                choices=[
                    ("stroller", "ベビーカー"),
                    ("cardboard", "ダンボール"),
                    ("suitcase", "スーツケース"),
                    ("other", "その他"),
                ],
                default="suitcase",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\+?1?\\d{9,15}$", "有効な電話番号が必要です。"
                    )
                ],
            ),
        ),
    ]
