# Generated by Django 5.0.14 on 2026-08-30 17:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_initial'),
        ('business_owners', '0001_initial'),
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAssignmentRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_date', models.DateField(db_index=True, verbose_name='割当対象日')),
                ('status', models.CharField(choices=[('queued', '実行待ち'), ('running', '自動割当中'), ('draft', '提案を確認中'), ('applied', '適用済み'), ('stale', '再割当が必要'), ('failed', '失敗')], db_index=True, default='queued', max_length=20, verbose_name='割当状態')),
                ('input_hash', models.CharField(max_length=64, verbose_name='入力ハッシュ')),
                ('selected_driver_ids', models.JSONField(blank=True, default=list, verbose_name='選択した配達者ID')),
                ('unassigned_tasks', models.JSONField(blank=True, default=list, verbose_name='未割当の集荷・配達')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='開始日時')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完了日時')),
                ('applied_at', models.DateTimeField(blank=True, null=True, verbose_name='適用日時')),
                ('business_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_runs', to='business_owners.businessprofile', verbose_name='事業者')),
            ],
            options={
                'verbose_name': '日次自動割当の実行記録',
                'verbose_name_plural': '日次自動割当の実行記録',
                'db_table': 'daily_assignment_runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyTaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('pickup', '集荷'), ('delivery', '配達')], max_length=10, verbose_name='集荷・配達の種別')),
                ('manually_assigned', models.BooleanField(default=False, verbose_name='手動割当')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_task_assignments', to='bookings.luggagebooking')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_task_assignments', to='drivers.driverprofile')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='routing.dailyassignmentrun')),
            ],
            options={
                'verbose_name': '集荷・配達ごとの担当割当',
                'verbose_name_plural': '集荷・配達ごとの担当割当',
                'db_table': 'daily_task_assignments',
                'ordering': ['driver_id', 'booking_id', 'kind'],
            },
        ),
        migrations.CreateModel(
            name='DriverRouteResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField(db_index=True, verbose_name='対象日')),
                ('input_hash', models.CharField(max_length=64, verbose_name='入力ハッシュ')),
                ('route', models.JSONField(default=dict, verbose_name='生成済みルート')),
                ('generated_at', models.DateTimeField(auto_now=True, verbose_name='生成日時')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_results', to='drivers.driverprofile')),
            ],
            options={
                'verbose_name': '配達者ルート保存結果',
                'verbose_name_plural': '配達者ルート保存結果',
                'db_table': 'driver_route_results',
            },
        ),
        migrations.AddConstraint(
            model_name='dailyassignmentrun',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['queued', 'running'])), fields=('business_owner', 'service_date'), name='uniq_active_routing_run_per_owner_date'),
        ),
        migrations.AddConstraint(
            model_name='dailytaskassignment',
            constraint=models.UniqueConstraint(fields=('run', 'booking', 'kind'), name='uniq_task_assignment_per_run'),
        ),
        migrations.AddConstraint(
            model_name='driverrouteresult',
            constraint=models.UniqueConstraint(fields=('driver', 'service_date'), name='uniq_route_result_per_driver_date'),
        ),
    ]
