# Generated by Django 5.0.14 on 2026-08-09 02:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0013_luggagebooking_delivery_geocode_status_and_more'),
        ('business_owners', '0010_rename_last_error_payoutdocumentdelivery_last_err_and_more'),
        ('drivers', '0002_driverprofile_departure_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAssignmentRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_date', models.DateField(db_index=True, verbose_name='割当対象日')),
                ('status', models.CharField(choices=[('queued', '実行待ち'), ('running', '自動割当中'), ('draft', '提案を確認中'), ('applied', '適用済み'), ('stale', '再割当が必要'), ('failed', '失敗')], db_index=True, default='queued', max_length=20, verbose_name='割当状態')),
                ('input_hash', models.CharField(max_length=64)),
                ('selected_driver_ids', models.JSONField(blank=True, default=list)),
                ('unassigned_tasks', models.JSONField(blank=True, default=list, verbose_name='未割当の集荷・配達')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='開始日時')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完了日時')),
                ('applied_at', models.DateTimeField(blank=True, null=True, verbose_name='適用日時')),
                ('business_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_runs', to='business_owners.businessprofile')),
            ],
            options={
                'verbose_name': '日次自動割当の実行記録',
                'verbose_name_plural': '日次自動割当の実行記録',
                'db_table': 'daily_assignment_runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyTaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('pickup', '集荷'), ('delivery', '配達')], max_length=10, verbose_name='集荷・配達の種別')),
                ('manually_assigned', models.BooleanField(default=False, verbose_name='手動割当')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_task_assignments', to='bookings.luggagebooking')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_task_assignments', to='drivers.driverprofile')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='routing.dailyassignmentrun')),
            ],
            options={
                'verbose_name': '集荷・配達ごとの担当割当',
                'verbose_name_plural': '集荷・配達ごとの担当割当',
                'db_table': 'daily_task_assignments',
                'ordering': ['driver_id', 'booking_id', 'kind'],
            },
        ),
        migrations.CreateModel(
            name='DriverDailyRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_duration_seconds', models.PositiveIntegerField(default=0, verbose_name='合計所要時間（秒）')),
                ('total_distance_meters', models.PositiveIntegerField(default=0, verbose_name='合計距離（メートル）')),
                ('stop_count', models.PositiveSmallIntegerField(default=0, verbose_name='訪問先数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_routes', to='drivers.driverprofile')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='routing.dailyassignmentrun')),
            ],
            options={
                'verbose_name': '配達者日次ルート',
                'verbose_name_plural': '配達者日次ルート',
                'db_table': 'driver_daily_routes',
            },
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('pickup', '集荷'), ('delivery', '配達')], max_length=10, verbose_name='集荷・配達の種別')),
                ('sequence', models.PositiveSmallIntegerField(verbose_name='訪問順')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('location_name', models.CharField(blank=True, default='', max_length=200, verbose_name='地点名')),
                ('location_address', models.TextField(blank=True, default='', verbose_name='住所')),
                ('planned_arrival_at', models.DateTimeField(blank=True, null=True, verbose_name='到着予定日時')),
                ('duration_from_previous_seconds', models.PositiveIntegerField(default=0, verbose_name='前地点からの所要時間（秒）')),
                ('distance_from_previous_meters', models.PositiveIntegerField(default=0, verbose_name='前地点からの距離（メートル）')),
                ('manually_assigned', models.BooleanField(default=False, verbose_name='手動割当')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='route_stops', to='bookings.luggagebooking')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='routing.driverdailyroute')),
            ],
            options={
                'verbose_name': 'ルート訪問先',
                'verbose_name_plural': 'ルート訪問先',
                'db_table': 'route_stops',
                'ordering': ['sequence'],
            },
        ),
        migrations.AddConstraint(
            model_name='dailyassignmentrun',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['queued', 'running'])), fields=('business_owner', 'service_date'), name='uniq_active_routing_run_per_owner_date'),
        ),
        migrations.AddConstraint(
            model_name='dailytaskassignment',
            constraint=models.UniqueConstraint(fields=('run', 'booking', 'kind'), name='uniq_task_assignment_per_run'),
        ),
        migrations.AddConstraint(
            model_name='driverdailyroute',
            constraint=models.UniqueConstraint(fields=('run', 'driver'), name='uniq_driver_route_per_run'),
        ),
        migrations.AddConstraint(
            model_name='routestop',
            constraint=models.UniqueConstraint(fields=('route', 'sequence'), name='uniq_stop_sequence_per_route'),
        ),
        migrations.AddConstraint(
            model_name='routestop',
            constraint=models.UniqueConstraint(fields=('route', 'booking', 'kind'), name='uniq_task_per_route'),
        ),
    ]
