# Generated by Django 5.0.14 on 2026-08-19 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_driverprofile_departure_address_and_more'),
        ('routing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routestop',
            name='route',
        ),
        migrations.RemoveField(
            model_name='routestop',
            name='booking',
        ),
        migrations.CreateModel(
            name='DriverRouteResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField(db_index=True, verbose_name='対象日')),
                ('input_hash', models.CharField(max_length=64, verbose_name='入力ハッシュ')),
                ('route', models.JSONField(default=dict, verbose_name='生成済みルート')),
                ('generated_at', models.DateTimeField(auto_now=True, verbose_name='生成日時')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_results', to='drivers.driverprofile')),
            ],
            options={
                'verbose_name': '配達者ルート保存結果',
                'verbose_name_plural': '配達者ルート保存結果',
                'db_table': 'driver_route_results',
            },
        ),
        migrations.DeleteModel(
            name='DriverDailyRoute',
        ),
        migrations.DeleteModel(
            name='RouteStop',
        ),
        migrations.AddConstraint(
            model_name='driverrouteresult',
            constraint=models.UniqueConstraint(fields=('driver', 'service_date'), name='uniq_route_result_per_driver_date'),
        ),
    ]
