# Generated by Django 5.0.14 on 2026-09-09 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyassignmentrun',
            name='status',
            field=models.CharField(choices=[('queued', '実行待ち'), ('running', '自動割当中'), ('draft', '提案を確認中'), ('applied', '適用済み'), ('stale', '再割当が必要'), ('failed', '失敗'), ('cancelled', 'キャンセル済み')], db_index=True, default='queued', max_length=20, verbose_name='割当状態'),
        ),
    ]
