# Generated by Django 5.0.14 on 2026-08-22 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_owners', '0011_alter_payoutdocumentdelivery_options_and_more'),
        ('routing', '0002_remove_routestop_route_remove_routestop_booking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyassignmentrun',
            name='business_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_runs', to='business_owners.businessprofile', verbose_name='事業者'),
        ),
        migrations.AlterField(
            model_name='dailyassignmentrun',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='dailyassignmentrun',
            name='input_hash',
            field=models.CharField(max_length=64, verbose_name='入力ハッシュ'),
        ),
        migrations.AlterField(
            model_name='dailyassignmentrun',
            name='selected_driver_ids',
            field=models.JSONField(blank=True, default=list, verbose_name='選択した配達者ID'),
        ),
        migrations.AlterField(
            model_name='dailytaskassignment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
        ),
    ]
