# Generated by Django 5.0.14 on 2025-12-12 14:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business_owners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LuggageBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('delivery_status', models.CharField(choices=[('before_pickup', '集荷前'), ('picked_up', '集荷済'), ('delivered', '配達済'), ('cancelled', 'キャンセル')], default='before_pickup', max_length=20, verbose_name='配達状況')),
                ('pickup_location_name', models.CharField(max_length=200, verbose_name='集荷場所の名称')),
                ('pickup_location_address', models.TextField(verbose_name='集荷場所の住所')),
                ('pickup_date', models.DateField(verbose_name='集荷日')),
                ('delivery_location_name', models.CharField(max_length=200, verbose_name='配送場所の名称')),
                ('delivery_location_address', models.TextField(verbose_name='配送場所の住所')),
                ('delivery_date', models.DateField(verbose_name='配送日')),
                ('notes', models.TextField(blank=True, verbose_name='備考')),
                ('luggage_items', models.JSONField(default=dict, verbose_name='荷物情報')),
                ('total_amount', models.PositiveIntegerField(default=0, verbose_name='合計金額')),
                ('customer_name', models.CharField(max_length=200, verbose_name='顧客名')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='メールアドレス')),
                ('customer_phone_number', models.CharField(max_length=15, verbose_name='電話番号')),
                ('customer_nationality', models.CharField(max_length=3, verbose_name='国籍')),
                ('guest_name', models.CharField(max_length=200, verbose_name='宿泊予約者名')),
                ('payment_intent_id', models.CharField(max_length=255, verbose_name='Stripe Payment Intent ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('business_owner', models.ForeignKey(blank=True, help_text='この予約を担当するビジネスオーナー', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='business_owners.businessprofile', verbose_name='ビジネスオーナー')),
            ],
            options={
                'verbose_name': '予約情報',
                'verbose_name_plural': '予約情報',
                'db_table': 'luggage_bookings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['delivery_status'], name='luggage_boo_deliver_566e65_idx'), models.Index(fields=['pickup_date'], name='luggage_boo_pickup__96d44a_idx'), models.Index(fields=['delivery_date'], name='luggage_boo_deliver_bb50d3_idx'), models.Index(fields=['customer_name'], name='luggage_boo_custome_8ed5c4_idx')],
            },
        ),
    ]
