# Generated by Django 5.0.14 on 2026-08-30 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('business_owners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargedispute',
            name='business_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes', to='business_owners.businessprofile', verbose_name='事業者'),
        ),
        migrations.AddField(
            model_name='luggagebooking',
            name='business_owner',
            field=models.ForeignKey(help_text='この予約を担当する事業者', on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='business_owners.businessprofile', verbose_name='事業者'),
        ),
    ]
