# Generated by Django 5.0.14 on 2026-03-24 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_luggagebooking_created_at_and_more'),
        ('business_owners', '0004_businessprofile_pricing_draft_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='luggagebooking',
            name='business_owner',
            field=models.ForeignKey(blank=True, help_text='この予約を担当する事業者', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='business_owners.businessprofile', verbose_name='事業者'),
        ),
    ]
