# Generated by Django 5.0.14 on 2026-08-30 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_initial'),
        ('business_owners', '0001_initial'),
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='luggagebooking',
            name='driver',
            field=models.ForeignKey(blank=True, help_text='この予約の配達担当者。集荷担当未指定時は集荷も担当する', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bookings', to='drivers.driverprofile', verbose_name='配達者'),
        ),
        migrations.AddField(
            model_name='luggagebooking',
            name='pickup_driver',
            field=models.ForeignKey(blank=True, help_text='配達担当者と集荷担当者を分ける場合のみ指定する', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_assigned_bookings', to='drivers.driverprofile', verbose_name='集荷担当者'),
        ),
        migrations.AddField(
            model_name='chargedispute',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes', to='bookings.luggagebooking', verbose_name='対応する予約'),
        ),
        migrations.AddField(
            model_name='bookingauditlog',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='bookings.luggagebooking', verbose_name='対応する予約'),
        ),
        migrations.AddField(
            model_name='pendingbooking',
            name='business_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pending_bookings', to='business_owners.businessprofile', verbose_name='事業者'),
        ),
        migrations.AddIndex(
            model_name='luggagebooking',
            index=models.Index(fields=['delivery_status'], name='luggage_boo_deliver_566e65_idx'),
        ),
        migrations.AddIndex(
            model_name='luggagebooking',
            index=models.Index(fields=['pickup_date'], name='luggage_boo_pickup__96d44a_idx'),
        ),
        migrations.AddIndex(
            model_name='luggagebooking',
            index=models.Index(fields=['delivery_date'], name='luggage_boo_deliver_bb50d3_idx'),
        ),
        migrations.AddIndex(
            model_name='luggagebooking',
            index=models.Index(fields=['customer_name'], name='luggage_boo_custome_8ed5c4_idx'),
        ),
        migrations.AddIndex(
            model_name='luggagebooking',
            index=models.Index(fields=['delivered_at'], name='luggage_boo_deliver_de12ef_idx'),
        ),
        migrations.AddIndex(
            model_name='luggagebooking',
            index=models.Index(fields=['business_owner', 'pickup_date'], name='luggage_boo_busines_494cd7_idx'),
        ),
        migrations.AddIndex(
            model_name='luggagebooking',
            index=models.Index(fields=['business_owner', 'delivery_date'], name='luggage_boo_busines_35252f_idx'),
        ),
        migrations.AddIndex(
            model_name='luggagebooking',
            index=models.Index(fields=['business_owner', 'delivery_status'], name='luggage_boo_busines_6fbc84_idx'),
        ),
        migrations.AddConstraint(
            model_name='luggagebooking',
            constraint=models.UniqueConstraint(condition=models.Q(('payment_intent_id', ''), _negated=True), fields=('payment_intent_id',), name='uniq_booking_payment_intent_id'),
        ),
        migrations.AddIndex(
            model_name='bookingauditlog',
            index=models.Index(fields=['action'], name='booking_aud_action_21a1d3_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingauditlog',
            index=models.Index(fields=['source'], name='booking_aud_source_95f1fc_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingauditlog',
            index=models.Index(fields=['created_at'], name='booking_aud_created_5bb4ff_idx'),
        ),
    ]
