# Generated by Django 5.0.14 on 2026-06-25 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_luggagebooking_business_owner'),
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='luggagebooking',
            name='driver',
            field=models.ForeignKey(blank=True, help_text='この予約を担当する配達者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bookings', to='drivers.driverprofile', verbose_name='配達者'),
        ),
    ]
