# Generated by Django 5.0.14 on 2026-07-03 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_luggagebooking_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='luggagebooking',
            name='issuer_address',
            field=models.TextField(blank=True, default='', verbose_name='発行者住所（スナップショット）'),
        ),
        migrations.AddField(
            model_name='luggagebooking',
            name='issuer_email',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='発行者メール（スナップショット）'),
        ),
        migrations.AddField(
            model_name='luggagebooking',
            name='issuer_invoice_number',
            field=models.CharField(blank=True, default='', max_length=14, verbose_name='適格請求書発行事業者登録番号（スナップショット）'),
        ),
        migrations.AddField(
            model_name='luggagebooking',
            name='issuer_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='発行者名（スナップショット）'),
        ),
        migrations.AddField(
            model_name='luggagebooking',
            name='issuer_phone',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='発行者電話番号（スナップショット）'),
        ),
        migrations.AddField(
            model_name='luggagebooking',
            name='issuer_snapshot_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='発行者情報スナップショット保存日時'),
        ),
    ]
