# Generated by Django 5.0.14 on 2026-07-05 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_luggagebooking_issuer_address_and_more'),
        ('business_owners', '0006_businessprofile_invoice_registration_number_and_more'),
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_intent_id', models.CharField(max_length=255, unique=True, verbose_name='Stripe Payment Intent ID')),
                ('payload', models.JSONField(default=dict, verbose_name='予約作成用データ')),
                ('total_amount', models.PositiveIntegerField(default=0, verbose_name='合計金額')),
                ('consumed_at', models.DateTimeField(blank=True, null=True, verbose_name='予約作成完了日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
            ],
            options={
                'verbose_name': '保留中の予約（フォールバック用）',
                'verbose_name_plural': '保留中の予約（フォールバック用）',
                'db_table': 'pending_bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='luggagebooking',
            constraint=models.UniqueConstraint(condition=models.Q(('payment_intent_id', ''), _negated=True), fields=('payment_intent_id',), name='uniq_booking_payment_intent_id'),
        ),
        migrations.AddField(
            model_name='pendingbooking',
            name='business_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pending_bookings', to='business_owners.businessprofile', verbose_name='事業者'),
        ),
    ]
