# Generated by Django 5.0.14 on 2026-07-07 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_pendingbooking_and_more'),
        ('business_owners', '0008_alter_businessprofile_stripe_account_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeDispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispute_id', models.CharField(max_length=255, unique=True, verbose_name='Stripe 異議申立て ID')),
                ('charge_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Stripe Charge ID')),
                ('payment_intent_id', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Stripe Payment Intent ID')),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='異議申立て金額')),
                ('currency', models.CharField(blank=True, default='', max_length=10, verbose_name='通貨')),
                ('reason', models.CharField(blank=True, default='', max_length=100, verbose_name='理由')),
                ('status', models.CharField(blank=True, default='', max_length=50, verbose_name='ステータス')),
                ('is_charge_refundable', models.BooleanField(default=False, verbose_name='チャージ返金可否')),
                ('evidence_due_by', models.DateTimeField(blank=True, null=True, verbose_name='証拠提出期限')),
                ('opened_at', models.DateTimeField(blank=True, null=True, verbose_name='異議申立て発生日時')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='クローズ日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes', to='bookings.luggagebooking', verbose_name='対応する予約')),
                ('business_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes', to='business_owners.businessprofile', verbose_name='事業者')),
            ],
            options={
                'verbose_name': 'チャージバック（異議申立て）',
                'verbose_name_plural': 'チャージバック（異議申立て）',
                'db_table': 'charge_disputes',
                'ordering': ['-created_at'],
            },
        ),
    ]
