# Generated by Django 5.0.14 on 2026-07-08 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_chargedispute'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=255, unique=True, verbose_name='Stripe Event ID')),
                ('event_type', models.CharField(blank=True, default='', max_length=100, verbose_name='イベント種別')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='受信日時')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='処理完了日時')),
            ],
            options={
                'verbose_name': 'Stripe Webhook イベント',
                'verbose_name_plural': 'Stripe Webhook イベント',
                'db_table': 'stripe_webhook_events',
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddField(
            model_name='luggagebooking',
            name='refund_reconciled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='返金整合性チェック日時'),
        ),
        migrations.AddField(
            model_name='luggagebooking',
            name='refund_status',
            field=models.CharField(choices=[('none', '返金なし'), ('pending', '返金処理中'), ('succeeded', '返金完了'), ('failed', '返金失敗'), ('canceled', '返金取消')], db_index=True, default='none', max_length=20, verbose_name='返金状況'),
        ),
        migrations.AddField(
            model_name='luggagebooking',
            name='refunded_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='返金済み金額'),
        ),
        migrations.AddField(
            model_name='luggagebooking',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='返金完了日時'),
        ),
        migrations.AddField(
            model_name='luggagebooking',
            name='stripe_charge_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Stripe Charge ID'),
        ),
        migrations.AddField(
            model_name='luggagebooking',
            name='stripe_refund_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Stripe Refund ID'),
        ),
        migrations.CreateModel(
            name='BookingAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_intent_id', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Stripe Payment Intent ID')),
                ('action', models.CharField(choices=[('refund_requested', '返金リクエスト'), ('refund_succeeded', '返金完了'), ('refund_pending', '返金処理中'), ('refund_failed', '返金失敗'), ('refund_canceled', '返金取消'), ('booking_cancelled', '予約キャンセル'), ('reconciled', '整合性同期')], max_length=40, verbose_name='操作')),
                ('source', models.CharField(choices=[('owner_api', '事業者API'), ('customer_api', '顧客API'), ('webhook', 'Stripe Webhook'), ('dashboard', 'Stripe ダッシュボード（手動）'), ('system', 'システム')], max_length=20, verbose_name='発生経路')),
                ('previous_delivery_status', models.CharField(blank=True, default='', max_length=20, verbose_name='変更前の配達状況')),
                ('new_delivery_status', models.CharField(blank=True, default='', max_length=20, verbose_name='変更後の配達状況')),
                ('previous_refund_status', models.CharField(blank=True, default='', max_length=20, verbose_name='変更前の返金状況')),
                ('new_refund_status', models.CharField(blank=True, default='', max_length=20, verbose_name='変更後の返金状況')),
                ('stripe_event_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Stripe Event ID')),
                ('stripe_refund_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Stripe Refund ID')),
                ('stripe_charge_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Stripe Charge ID')),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='金額')),
                ('message', models.TextField(blank=True, default='', verbose_name='メモ')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='付随情報')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='記録日時')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='bookings.luggagebooking', verbose_name='対応する予約')),
            ],
            options={
                'verbose_name': '予約監査ログ',
                'verbose_name_plural': '予約監査ログ',
                'db_table': 'booking_audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action'], name='booking_aud_action_21a1d3_idx'), models.Index(fields=['source'], name='booking_aud_source_95f1fc_idx'), models.Index(fields=['created_at'], name='booking_aud_created_5bb4ff_idx')],
            },
        ),
    ]
