# Generated by Django 5.0.14 on 2026-07-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_stripewebhookevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='luggagebooking',
            name='customer_language',
            field=models.CharField(choices=[('ja', '日本語'), ('en', '英語'), ('zh-Hans', '中国語（簡体字）'), ('zh-Hant', '中国語（繁体字）')], default='ja', max_length=10, verbose_name='顧客の表示言語'),
        ),
        migrations.AddField(
            model_name='luggagebooking',
            name='delivery_location_address_ja',
            field=models.TextField(blank=True, default='', help_text='非日本語で予約された場合の日本語表記（事業者の予約一覧用）', verbose_name='配送場所の住所（日本語）'),
        ),
        migrations.AddField(
            model_name='luggagebooking',
            name='delivery_location_name_ja',
            field=models.CharField(blank=True, default='', help_text='非日本語で予約された場合の日本語表記（事業者の予約一覧用）', max_length=200, verbose_name='配送場所の名称（日本語）'),
        ),
        migrations.AddField(
            model_name='luggagebooking',
            name='pickup_location_address_ja',
            field=models.TextField(blank=True, default='', help_text='非日本語で予約された場合の日本語表記（事業者の予約一覧用）', verbose_name='集荷場所の住所（日本語）'),
        ),
        migrations.AddField(
            model_name='luggagebooking',
            name='pickup_location_name_ja',
            field=models.CharField(blank=True, default='', help_text='非日本語で予約された場合の日本語表記（事業者の予約一覧用）', max_length=200, verbose_name='集荷場所の名称（日本語）'),
        ),
        migrations.AlterField(
            model_name='luggagebooking',
            name='customer_phone_number',
            field=models.CharField(max_length=16, verbose_name='電話番号'),
        ),
    ]
