# Generated by Django 5.0.14 on 2026-07-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_luggagebooking_customer_language_and_more'),
        ('business_owners', '0008_alter_businessprofile_stripe_account_id'),
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='luggagebooking',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='配達完了日時'),
        ),
        migrations.AddField(
            model_name='luggagebooking',
            name='funds_available_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Stripe資金の入金可能日時'),
        ),
        migrations.AddField(
            model_name='luggagebooking',
            name='stripe_transfer_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Stripe Transfer ID'),
        ),
        migrations.AddField(
            model_name='luggagebooking',
            name='transferred_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='事業者への送金日時'),
        ),
        migrations.AlterField(
            model_name='bookingauditlog',
            name='action',
            field=models.CharField(choices=[('refund_requested', '返金リクエスト'), ('refund_succeeded', '返金完了'), ('refund_pending', '返金処理中'), ('refund_failed', '返金失敗'), ('refund_canceled', '返金取消'), ('booking_cancelled', '予約キャンセル'), ('reconciled', '整合性同期'), ('transfer_created', '事業者への送金')], max_length=40, verbose_name='操作'),
        ),
        migrations.AddIndex(
            model_name='luggagebooking',
            index=models.Index(fields=['delivered_at'], name='luggage_boo_deliver_de12ef_idx'),
        ),
    ]
