# Generated by Django 5.0.14 on 2026-07-21 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_luggagebooking_transfer_amount_snapshots'),
    ]

    operations = [
        migrations.AddField(
            model_name='luggagebooking',
            name='issuer_name_en',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='発行者名英語表記（スナップショット）'),
        ),
    ]
