# Generated by Django 5.0.14 on 2026-08-09 02:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_luggagebooking_issuer_name_en'),
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='luggagebooking',
            name='delivery_geocode_status',
            field=models.CharField(choices=[('pending', '未処理'), ('verified', '確認済み'), ('approximate', '概算'), ('failed', '失敗')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='luggagebooking',
            name='delivery_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AddField(
            model_name='luggagebooking',
            name='delivery_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AddField(
            model_name='luggagebooking',
            name='delivery_manually_assigned',
            field=models.BooleanField(default=False, help_text='人が手動で配達担当を付けた場合に True。自動割当では False', verbose_name='配達の手動割当'),
        ),
        migrations.AddField(
            model_name='luggagebooking',
            name='delivery_place_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='luggagebooking',
            name='delivery_postal_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='luggagebooking',
            name='pickup_driver',
            field=models.ForeignKey(blank=True, help_text='配達担当者と集荷担当者を分ける場合のみ指定する', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_assigned_bookings', to='drivers.driverprofile', verbose_name='集荷担当者'),
        ),
        migrations.AddField(
            model_name='luggagebooking',
            name='pickup_geocode_status',
            field=models.CharField(choices=[('pending', '未処理'), ('verified', '確認済み'), ('approximate', '概算'), ('failed', '失敗')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='luggagebooking',
            name='pickup_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AddField(
            model_name='luggagebooking',
            name='pickup_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AddField(
            model_name='luggagebooking',
            name='pickup_manually_assigned',
            field=models.BooleanField(default=False, help_text='人が手動で集荷担当を付けた場合に True。自動割当では False', verbose_name='集荷の手動割当'),
        ),
        migrations.AddField(
            model_name='luggagebooking',
            name='pickup_place_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='luggagebooking',
            name='pickup_postal_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='bookingauditlog',
            name='action',
            field=models.CharField(choices=[('refund_requested', '返金リクエスト'), ('refund_succeeded', '返金完了'), ('refund_pending', '返金処理中'), ('refund_failed', '返金失敗'), ('refund_canceled', '返金取消'), ('booking_cancelled', '予約キャンセル'), ('reconciled', '整合性同期'), ('transfer_created', '事業者への送金'), ('auto_assigned', '自動割当による担当割当')], max_length=40, verbose_name='操作'),
        ),
        migrations.AlterField(
            model_name='luggagebooking',
            name='driver',
            field=models.ForeignKey(blank=True, help_text='この予約の配達担当者。集荷担当未指定時は集荷も担当する', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bookings', to='drivers.driverprofile', verbose_name='配達者'),
        ),
    ]
