# Generated by Django 5.0.14 on 2026-08-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_luggagebooking_delivery_geocode_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='luggagebooking',
            name='delivery_signature',
            field=models.TextField(blank=True, default='', verbose_name='配達完了時の手書きサイン'),
        ),
        migrations.AddField(
            model_name='luggagebooking',
            name='facility_fee',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='施設側の手数料（円）'),
        ),
        migrations.AddField(
            model_name='luggagebooking',
            name='picked_up_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='集荷完了日時'),
        ),
        migrations.AddField(
            model_name='luggagebooking',
            name='transport_cost',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='高速代などの交通費（円）'),
        ),
    ]
