# Generated by Django 5.0.14 on 2026-08-22 16:17

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0014_luggagebooking_delivery_signature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingauditlog',
            name='new_delivery_status',
            field=models.CharField(blank=True, choices=[('before_pickup', '集荷前'), ('picked_up', '集荷済'), ('delivered', '配達済'), ('cancelled', 'キャンセル')], default='', max_length=20, verbose_name='変更後の配達状況'),
        ),
        migrations.AlterField(
            model_name='bookingauditlog',
            name='new_refund_status',
            field=models.CharField(blank=True, choices=[('none', '返金なし'), ('pending', '返金処理中'), ('succeeded', '返金完了'), ('failed', '返金失敗'), ('canceled', '返金取消')], default='', max_length=20, verbose_name='変更後の返金状況'),
        ),
        migrations.AlterField(
            model_name='bookingauditlog',
            name='previous_delivery_status',
            field=models.CharField(blank=True, choices=[('before_pickup', '集荷前'), ('picked_up', '集荷済'), ('delivered', '配達済'), ('cancelled', 'キャンセル')], default='', max_length=20, verbose_name='変更前の配達状況'),
        ),
        migrations.AlterField(
            model_name='bookingauditlog',
            name='previous_refund_status',
            field=models.CharField(blank=True, choices=[('none', '返金なし'), ('pending', '返金処理中'), ('succeeded', '返金完了'), ('failed', '返金失敗'), ('canceled', '返金取消')], default='', max_length=20, verbose_name='変更前の返金状況'),
        ),
        migrations.AlterField(
            model_name='chargedispute',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='chargedispute',
            name='evidence_due_by',
            field=models.DateTimeField(blank=True, null=True, verbose_name='証拠提出期限日時'),
        ),
        migrations.AlterField(
            model_name='chargedispute',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='luggagebooking',
            name='booking_number',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='予約番号'),
        ),
        migrations.AlterField(
            model_name='luggagebooking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='予約日時'),
        ),
        migrations.AlterField(
            model_name='luggagebooking',
            name='delivery_date',
            field=models.DateField(verbose_name='配達日'),
        ),
        migrations.AlterField(
            model_name='luggagebooking',
            name='delivery_geocode_status',
            field=models.CharField(choices=[('pending', '未処理'), ('verified', '確認済み'), ('approximate', '概算'), ('failed', '失敗')], db_index=True, default='pending', max_length=20, verbose_name='配達場所のジオコード状態'),
        ),
        migrations.AlterField(
            model_name='luggagebooking',
            name='delivery_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='配達場所の緯度'),
        ),
        migrations.AlterField(
            model_name='luggagebooking',
            name='delivery_location_address',
            field=models.TextField(verbose_name='配達場所の住所'),
        ),
        migrations.AlterField(
            model_name='luggagebooking',
            name='delivery_location_address_ja',
            field=models.TextField(blank=True, default='', help_text='非日本語で予約された場合の日本語表記（事業者の予約一覧用）', verbose_name='配達場所の住所（日本語）'),
        ),
        migrations.AlterField(
            model_name='luggagebooking',
            name='delivery_location_name',
            field=models.CharField(max_length=200, verbose_name='配達場所の名称'),
        ),
        migrations.AlterField(
            model_name='luggagebooking',
            name='delivery_location_name_ja',
            field=models.CharField(blank=True, default='', help_text='非日本語で予約された場合の日本語表記（事業者の予約一覧用）', max_length=200, verbose_name='配達場所の名称（日本語）'),
        ),
        migrations.AlterField(
            model_name='luggagebooking',
            name='delivery_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='配達場所の経度'),
        ),
        migrations.AlterField(
            model_name='luggagebooking',
            name='delivery_place_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='配達場所の Place ID'),
        ),
        migrations.AlterField(
            model_name='luggagebooking',
            name='delivery_postal_code',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='配達場所の郵便番号'),
        ),
        migrations.AlterField(
            model_name='luggagebooking',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='luggagebooking',
            name='pickup_geocode_status',
            field=models.CharField(choices=[('pending', '未処理'), ('verified', '確認済み'), ('approximate', '概算'), ('failed', '失敗')], db_index=True, default='pending', max_length=20, verbose_name='集荷場所のジオコード状態'),
        ),
        migrations.AlterField(
            model_name='luggagebooking',
            name='pickup_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='集荷場所の緯度'),
        ),
        migrations.AlterField(
            model_name='luggagebooking',
            name='pickup_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='集荷場所の経度'),
        ),
        migrations.AlterField(
            model_name='luggagebooking',
            name='pickup_place_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='集荷場所の Place ID'),
        ),
        migrations.AlterField(
            model_name='luggagebooking',
            name='pickup_postal_code',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='集荷場所の郵便番号'),
        ),
        migrations.AlterField(
            model_name='luggagebooking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='pendingbooking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='pendingbooking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
    ]
