# Generated by Django 5.0.14 on 2026-08-29 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0015_alter_bookingauditlog_new_delivery_status_and_more'),
        ('business_owners', '0011_alter_payoutdocumentdelivery_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='luggagebooking',
            name='business_owner',
            field=models.ForeignKey(help_text='この予約を担当する事業者', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='business_owners.businessprofile', verbose_name='事業者'),
        ),
    ]
